### ISSUE TITLE
Cannot redeclare wp_check_password()

### ISSUE THREAD

**Issue by rtpHarry** [roots/wp-password-bcrypt#11]
I saw that #7 has already come and gone but I have just experienced this in a different situation.

I have a dev box running `PHP Version 5.5.9-1ubuntu4.11` according to `phpinfo()`.

I installed the plugin by downloading the master.zip from github and extracting to the correct plugins folder.

When I activated it I saw this error:

```
Fatal error: Cannot redeclare wp_check_password() (previously declared in /srv/www/basetemplate/htdocs/wp-includes/pluggable.php:2087) in /srv/www/basetemplate/htdocs/wp-content/plugins/wp-password-bcrypt/wp-password-bcrypt.php on line 24
```

I'm not using the mu stuff, I didn't use composer, I did renamed the folder to remove the -master, I am using the latest Sage as the theme.

**Comment by QWp6t** [comment]
This plugin follows the correct parameters to override core pluggable functions. You can post about it on [discourse.roots.io](https://discourse.roots.io/) if you want to reach out to the community for help, but this is not a bug with the plugin. It is likely an issue on your end, or it's an issue created by some other third-party.

**Comment by Jeger** [comment]
> This plugin follows the correct parameters to override core pluggable functions.

Respectfully, I don't think it does. 

From the [codex](https://codex.wordpress.org/Pluggable_Functions):
> For safety, it is best to always wrap your functions with if ( !function_exists() ), otherwise you will produce fatal errors on plugin activation.

**Comment by szepeviktor** [comment]
Implemented in my WP.org fork.
https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=1458455%40password-bcrypt&old=1415854%40password-bcrypt#file7
