### ISSUE TITLE
Please make this available in the main WordPress plugins directory

### ISSUE THREAD

**Issue by ianchanning** [roots/wp-password-bcrypt#13]
This is a fantastic plugin but I worry that it will be criminally under used because it's not in the main WordPress plugins directory:

As far as I can tell this is because in the roots ecosystem you consider doing everything via Composer as the normal / best way to do it, plus your concerns about someone disabling the plugin:

> As explained above, you don't want to disable this plugin once you've enabled it. Installing this in plugins (as a "normal" plugin) instead of in mu-plugins (as a must-use plugin) makes it possible for an admin user to accidentally disable it.

If you add it to the WordPress plugins directory then:

1. It makes it much easier for people to install - the vast majority of WordPress users don't use Composer
2. Any security updates you make for this will be automatically highlighted to users

Surely the point of this plugin is to help all WordPress users improve their security? The risk that some admins will disable the plugin (which would be odd when it's likely that they would have been the ones to install it), seems relatively smaller than the benefits.

Perhaps there's some other restrictions on the WordPress plugins directory that I don't know about.

**Comment by ianchanning** [comment]
On a connected note this [comment][1] from @Foxaii in response to a separate Pull request:

> By using a non-system default, this PR would require users to update the plugin whenever a newer version of PHP increases the cost. That's not a lot of maintenance to ask of a developer, but could easily be missed by end users, more so given that we suggest the plugin is used as a composer dependancy or mu-plugin.

It doesn't matter whether you actually want to implement the pull request in question. What does matter is that when a pull request comes along that you *do* want to push out there's no easy way to inform all the users of this plugin.

  [1]: https://github.com/roots/wp-password-bcrypt/pull/8#issuecomment-193462276

**Comment by retlehs** [comment]
discussed previously at https://discourse.roots.io/t/improving-wordpress-passwords-security/6074/20?u=benword

**Comment by szepeviktor** [comment]
@ianchanning I could try releasing it on WP.org.

**Comment by ianchanning** [comment]
@szepeviktor yeah, sure, if not I can too. I've got one plugin in the WordPress directory and I know there's automatic pipelines you can set up between github and the WordPress directory, but I had just assumed that there was more integration between the roots ecosystem and the WordPress directory

**Comment by ianchanning** [comment]
@retlehs I've got to say that I'm surprised that the roots folks don't have other plugins in the WordPress directory. From the discussion, I've got to say this really surprised me:

> Not really. We generally avoid the ".org" ecosystem. However, it might be pretty simple to just publish this plugin there. I have no idea what the process is and I don't really want to get into SVN

All my clients still use SVN, so I'd be quite happy to release it to the WordPress directory, but then it wouldn't be an 'official' plugin.

**Comment by szepeviktor** [comment]
Here it is https://wordpress.org/plugins/password-bcrypt/

**Comment by ianchanning** [comment]
Great stuff. Slight change that needs to be made is that the minimum WordPress version should be 4.4, not 4.0 as you've got. As per [comment above](https://github.com/roots/wp-password-bcrypt/issues/13#issuecomment-218455401) and this has been added to the master `README.md` too.

**Comment by swalkinshaw** [comment]
@szepeviktor if you're going to do this at least follow on our license: https://github.com/roots/wp-password-bcrypt/blob/master/LICENSE.md

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by retlehs** [comment]
💩

**Comment by szepeviktor** [comment]
Excuse me.
https://github.com/szepeviktor/password-bcrypt
https://wordpress.org/plugins/password-bcrypt/changelog/ (wait for the cache)
