### ISSUE TITLE
Cannot redeclare wp_check_password()

### ISSUE THREAD

**Issue by ClicksFix** [roots/wp-password-bcrypt#19]
## Bug report

**Please provide steps to reproduce, including full log output:**

Occurs each time I attempt to go to my plugins page. I am unable to access my plugins page. Each time I do I receive this in my logs:

_PHP Fatal error:  Cannot redeclare wp_check_password() (previously declared in /xxxxx/xxxxx/xxxxx/wp-includes/pluggable.php:2126) in /xxxxx/xxxxx/xxxxx/wp-content/mu-plugins/wp-password-bcrypt.php on line 24_

**Please describe your local environment:**

wp-password-bcrypt version: 1.0

WordPress version: 4.8.2

**Where did the bug happen? Development or remote servers?**

Remote servers

**Comment by renatonascalves** [comment]
I think you are using the composer version and also on the mu-plugins folder. Did you check it?

**Comment by ClicksFix** [comment]
@renatonascalves I'm not using Composer. I've manually copied `wp-password-bcrypt.php` into my `mu-plugins` folder (as discussed [here](https://github.com/roots/wp-password-bcrypt#manually-as-a-must-use-plugin)). Did I install it incorrectly? It's been working for over a year now on my installation without any issues.

**Comment by renatonascalves** [comment]
@ClicksFix Can you do a search on the plugins installed? Especially security related plugins?

**Comment by ClicksFix** [comment]
@renatonascalves Sorry for such a long delay in getting back. I haven't had much time to troubleshoot this, but I was finally able to get to do so. You're correct, it had to deal with a security plugin. When removed it doesn't have this issue.

Thanks for your time provided to resolve this.

**Comment by renatonascalves** [comment]
@ClicksFix Good to know! :)
