### ISSUE TITLE
composer.json needs: "type": "wordpress-plugin",

### ISSUE THREAD

**Issue by pryley** [roots/wp-password-bcrypt#20]
In order to use this plugin with composer, the type needs to be added to the composer.json file:

```json
{
    "type": "wordpress-plugin"
}
```

**Comment by retlehs** [comment]
not true. https://github.com/roots/wp-password-bcrypt#composer-autoloaded

there's over 500k installs of this plugin via composer 😉

**Comment by pryley** [comment]
I have also been using it through composer for a long time (see [Dioscuri](https://github.com/geminilabs/dioscuri/blob/master/composer.json)).

**However**, while composer pulls it into the project, [composer installers](https://github.com/composer/installers) is not able to place it into the mu-plugins directory because the "type" has not been defined in the composer.json file.

As you can see in [composer installers readme example](https://github.com/composer/installers#example-composerjson-file), it says that the two required values to put in your composer.json file are the "type" and "require" values.

The "type" value describes what your package is (i.e. "wordpress-plugoin") and the "require" value tells composer to load the custom installers.

This is easily verified.

**Comment by retlehs** [comment]
you're trying to load it via composer _and_ use it as a mu-plugin? that's not how this project works

please read the README once again.

* https://github.com/roots/wp-password-bcrypt#composer-autoloaded
* https://github.com/roots/wp-password-bcrypt#manually-as-a-must-use-plugin

**Comment by kalenjohnson** [comment]
https://github.com/roots/wp-password-bcrypt/blob/master/composer.json#L39-L41

**Comment by ramonfincken** [comment]
Why dont you bash the end result in which you move the plugin to the mu-plugins folder (and make it work due to auto include of *.php)  ?

**Comment by pryley** [comment]
This is the standard way to install a wordpress plugin with composer-installers to the mu-plugins directory: https://github.com/geminilabs/dioscuri/blob/master/composer.json#L68-L75

I would prefer to stick to this method, however, yes I can script the end result to move it manually.

**Comment by retlehs** [comment]
for the third time, this is all covered in the README 😉

![image](https://user-images.githubusercontent.com/115911/36274911-7f9355c8-1246-11e8-819d-d0df1c9a4493.png)

![image](https://user-images.githubusercontent.com/115911/36274930-8e33c6e4-1246-11e8-8f98-22fc8a6f8e27.png)

**Comment by QWp6t** [comment]
You can use this instead if you want. https://wordpress.org/plugins/password-bcrypt/

It's not maintained by us, but  it's the same code.

`composer require wpackagist-plugin/password-bcrypt`

Just make sure to set it to install to `mu-plugins` in your **composer.json**, which you can do like this...

```diff
  "extra": {
    "installer-paths": {
-      "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
+      "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin", "wpackagist-plugin/password-bcrypt"],
      "web/app/plugins/{$name}/": ["type:wordpress-plugin"],
      "web/app/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  },
```
