### ISSUE TITLE
Github code needs update to 1.03 - fatal error: Cannot redeclare wp_check_password

### ISSUE THREAD

**Issue by franktjinaton** [roots/wp-password-bcrypt#21]
Installing this code give an error when installing on WP 4.9.6

Fatal error: Cannot redeclare wp_check_password() (previously declared in .../public_html/wp-includes/pluggable.php:2230) in .../public_html/wp-content/plugins/8020plugins/wp-password-bcrypt..php on line 44

The code on the WP directory works just fine - pls update github (or else delete it).
https://wordpress.org/plugins/password-bcrypt/

**Comment by renatonascalves** [comment]
@franktjinaton You have another plugin adding his plugin already. You need to remove one of them.

**Comment by franktjinaton** [comment]
@renatonascalves That was my first thought too - but after deactivating all other plugins I still got that error. Apart from that - the code is different than in the WP repo.

**Comment by szepeviktor** [comment]
@franktjinaton Please report the problem on WP.org, that is where I can support you.

**Comment by szepeviktor** [comment]
> The code on the WP directory works just fine

Oh! So my modified code is OK.

**Comment by QWp6t** [comment]
wp-settings.php loads all of WordPress's plugins (including this one) @ [L307](https://github.com/WordPress/WordPress/blob/a11d2f6a761d2c7a5c0c18d80d599105f34bf0cb/wp-settings.php#L307) whereas pluggable.php gets loaded a few lines later @ [L312](https://github.com/WordPress/WordPress/blob/a11d2f6a761d2c7a5c0c18d80d599105f34bf0cb/wp-settings.php#L312)

I don't see how it's possible for pluggable.php to get loaded before this plugin, as indicated in your error message, which suggests to me that there's something wrong with your setup.
