### ISSUE TITLE
Password resets when paired with Application Passwords

### ISSUE THREAD

**Issue by thefrosty** [roots/wp-password-bcrypt#22]
## Bug Report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/wp-password-bcrypt/issues)
- [X] I've read the [docs](https://github.com/roots/wp-password-bcrypt/blob/master/README.md) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

X When using this package paired with https://github.com/georgestephanis/application-passwords a users password (hash) is reset after every request using the app password.

**What is the expected or desired behavior?**

X A users password is not reset when making a basic auth request w/ the app password.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

- Install the Application Password plugin.
- Add an app password to your user (via your profile).
- Make an API request with no-auth and notice no change.
- Make an API request with your username and app password to any endpoint, and notice you're logged out of the WP admin, and your password hash has updated.

**Please describe your local environment:**

wp-password-bcrypt version: 1.0.0

WordPress version: 4.9.8

Active theme: twentyseventeen

Active plugins: application password

**Where did the bug happen? Development or remote servers?**

local & remote.

**Please provide a repository or your `wordpress_sites` config (if possible):**

N/A

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by thefrosty** [comment]
Since Application Passwords has been rolled into WordPress core as of 5.6, I would suggest marking this plugin as not compatible with WP >= 5.6, or fixing the issue.

**Comment by swalkinshaw** [comment]
@thefrosty do you have any idea what it would take to make this compatible? I'm not familiar with Application Passwords.

**Comment by swalkinshaw** [comment]
Going by your bug report, this plugin could only be causing an issue by calling `wp_set_password`. I doubt it's that function itself that we override.

My guess is it's this line: https://github.com/WordPress/wordpress-develop/blob/81b89682c387d47280c15105b9d3dd1af2f1e45a/src/wp-includes/user.php#L394

which calls this: https://github.com/roots/wp-password-bcrypt/blob/fb5bf95245ca5addbad8aadc9c9dd408c4126739/wp-password-bcrypt.php#L24-L44

And in some conditions, it does call `wp_set_password`. See https://github.com/roots/wp-password-bcrypt#wp_check_password for the explanation. 

I don't entirely know what's happening without debugging it, but it seems like we could skip this functionality for API authenticated requests by checking the `application_password_is_api_request` filter/hook?

**Comment by swalkinshaw** [comment]
It seems like the application passwords should be using bcrypt hashes as well since it uses `wp_hash_password` that this plugin overrides as well so I'd think this wouldn't cause any issues.

**Comment by swalkinshaw** [comment]
I can't reproduce this bug using WP 5.6 (built-in application passwords and *not* the plugin) with wp-password-bcrypt activated from the start. I created a new test user and generated an app password for them. Then made authenticated REST requests:

```plain
❯ curl --user "test:foo" http://example.test/wp-json/wp/v2/users
{"code":"incorrect_password","message":"The provided password is an invalid application password.","data":{"status":401}}
❯ curl --user "test:JbCW 3AQ3 JpbP bJnu mcCg J8tK" http://example.test/wp-json/wp/v2/users
[{"id":1,"name":"admin","url":"http:\/\/example.test\/wp","description":"","link":"http:\/\/example.test\/author\/admin\/","slug":"admin","avatar_urls":{"24":"http:\/\/2.gravatar.com\/avatar\/51965088c5db83c3fd307f308d25198a?s=24&d=mm&r=g","48":"http:\/\/2.gravatar.com\/avatar\/51965088c5db83c3fd307f308d25198a?s=48&d=mm&r=g","96":"http:\/\/2.gravatar.com\/avatar\/51965088c5db83c3fd307f308d25198a?s=96&d=mm&r=g"},"meta":[],"_links":{"self":[{"href":"http:\/\/example.test\/wp-json\/wp\/v2\/users\/1"}],"collection":[{"href":"http:\/\/example.test\/wp-json\/wp\/v2\/users"}]}}]
```

In both cases, neither the user's password hash *nor* the application password hash changed (and the user stayed logged in).

@thefrosty did you have the bcrypt plugin installed *before* using application passwords?

Since wp-password-bcrypt "upgrades" old legacy hashes to bcrypted ones but it only does that for the standard user password and not application passwords (since they never existed). We should probably update those as well for consistency and completeness.
