### ISSUE TITLE
Error: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by tillkruss** [roots/wp-password-bcrypt#24]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

We're seeing timeouts related to `wp_check_password()`.

Since we're running on Heroku, we can't increase the timeout of 30s.

We're also not seeing a stacktrace, just this:

```
Sentry\Exception\FatalErrorException: Error: Maximum execution time of 30 seconds exceeded
#0 /vendor/roots/wp-password-bcrypt/wp-password-bcrypt.php(42): null
```

Login and everything else works fine. We don't know what's actually failing.

**Comment by szepeviktor** [comment]
https://github.com/roots/wp-password-bcrypt/blob/master/wp-password-bcrypt.php#L42

**Comment by swalkinshaw** [comment]
This plugin is just calling a native PHP function so there's nothing we can do. If anything it seems like a Heroku issue.

**Comment by drzraf** [comment]
I'm getting this too, but:
1. I can't spot the origin (no backtrace)
2. The fact that it exceeds 30sec is suspicious
