### ISSUE TITLE
I'm locked out of my account

### ISSUE THREAD

**Issue by tomicakorac** [roots/wp-password-bcrypt#25]
I have a local installation of WP with Bedrock and I can't reset my password.

1. My local server can't send emails (so I can't reset my password in a normal way);
2. I've tried modifying my password from PhpMyAdmin using MD5 checksum, but that didn't work (I couldn't log in with the new password);
3. I've tried modifying my password from PhpMyAdmin by entering already encrypted password using this tool: https://passwordhashing.com/BCrypt?plainText=123456 and that didn't work either.

I am basically locked out of my website. What can I do to reset my password?

**Comment by szepeviktor** [comment]
Try https://github.com/szepeviktor/auto-login

**Comment by tomicakorac** [comment]
Wow, you're a life saver, @szepeviktor ! Thank you so much, this worked like a charm. Btw, great job with the plugin!

**Comment by szepeviktor** [comment]
I'm glad it sparked joy.
