### ISSUE TITLE
Make a new release that removes composer 1 dependency

### ISSUE THREAD

**Issue by pdebruic** [roots/wp-password-bcrypt#30]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x ] This request isn't a duplicate of an existing request
* [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

You've removed the dependency already in composer.json.  If you make a new release then a person could use composer 2.0+ to install it without adopting dev-master as their install target.

**Comment by swalkinshaw** [comment]
v1.1.0 was released
