### ISSUE TITLE
Removing the plugin afterwards

### ISSUE THREAD

**Issue by espellcaste** [roots/wp-password-bcrypt#5]
What if I remove the plugin later? The passwords would not convert into md5, so users wouldn't be able to log in, right?!

**Comment by swalkinshaw** [comment]
https://github.com/roots/wp-password-bcrypt#usage-warning

**Comment by espellcaste** [comment]
Got it! Thanks! 

That's what happens when you don't read, the answer was already there.

By the way, I was reading this article, https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016#php, last week and in my mind, I thought WordPress used bcrypt.

I guess lots of people, like me, sometimes think WordPress is on top of things and "trust" it to be secure and etc. Maybe we need more voices like yours to open our eyes.
