### ISSUE TITLE
Cannot redeclare wp_check_password()

### ISSUE THREAD

**Issue by lukecav** [roots/wp-password-bcrypt#7]
Fatal error: Cannot redeclare wp_check_password() (previously declared in C:\Users\johh-smith\Documents\Websites\test.dev\wp-includes\pluggable.php:2087) in C:\Users\john-smith\Documents\Websites\test.dev\wp-content\plugins\wp-password-bcrypt\wp-password-bcrypt.php on line 44

Just tried activating it on a local dev site using Desktop Server.

**Comment by lukecav** [comment]
$check = password_verify($password, $hash);
    return apply_filters('check_password', $check, $password, $hash, $userId);
}

**Comment by swalkinshaw** [comment]
Are you using Composer?

**Comment by lukecav** [comment]
Nope, it seems to work fine after I copied wp-password-bcrypt.php into your mu-plugins folder.

**Comment by jasonmader** [comment]
I saw the same Fatal error, but Iʼm not convinced it works in mu-plugins—since removing the plugin still allowed login.

**Comment by QWp6t** [comment]
When you install as mu-plugin you have to drop the PHP file directly into your `mu-plugins/` folder.

So it's `mu-plugins/wp-password-bcrypt.php`, i.e., not in its own sub-folder.

I'm guessing that was your issue @jasonmader. You can test it by visiting the plugins section of your admin panel. You should see the mu-plugin show up there in a mu-plugins section. If it's not there, then it's not being loaded as mu-plugin.

**Comment by jasonmader** [comment]
I did that. I don’t believe that’s the issue though. The same Fatal error may be still occuring, maybe the plugin is being ignored when it’s in the `mu-plugins/` folder. Login works fine with it, after removing it, login still works. If the hash had been changed, I wouldn’t expect login to work.

**Comment by swalkinshaw** [comment]
@jasonmader after about 30 minutes of us debugging this and going insane we figured out what's going on.

1. you installed the plugin
2. the users hash was generated by bcrypt and saved to the db
3. you removed the plugin
4. you tried to log in and it worked

We could also reproduce this and here's why. The end of result of logging in ends up [here](https://github.com/WordPress/WordPress/blob/e5ea82d81af2a6b5592fdd79974cad507f85c535/wp-includes/class-phpass.php#L270-L272).

```php
$hash = $this->crypt_private($password, $stored_hash);
if ($hash[0] == '*')
    $hash = crypt($password, $stored_hash);
```

In the case of a bcrypt hash, that conditional is true which results in `crypt` being called.

[`crypt`](http://php.net/manual/en/function.crypt.php) is a built-in PHP function which determines what hash type your PHP supports. In the case of PHP >= 5.5, it supports bcrypt (blowfish). Therefore it can still use bcrypt and everything works :clap:

**Comment by connorjburton** [comment]
Hi,

I am getting the same issue, using composer, it loads the library from the parent theme and a child theme is activated. I haven't done anything other than update my theme.

The parent theme uses Kernl.us for private repo hosting, so I pushed an update with the vendor folder containing `roots/wp-password-bcrypt `, updated the theme and now it gives me the same error as @lukecav

**Comment by swalkinshaw** [comment]
Pluggable functions are finalized before themes are loaded.
