### ISSUE TITLE
Migrate from wp-bcrypt

### ISSUE THREAD

**Issue by shazahm1** [roots/wp-password-bcrypt#9]
You mention other plugin in the FAQ. It would be nice to know if the [wp-bcrypt plugin](https://en-gb.wordpress.org/plugins/wp-bcrypt/) can be swapped with this one without affecting current user logins. I've been running the [wp-bcrypt plugin](https://en-gb.wordpress.org/plugins/wp-bcrypt/) plugin for at least a few years now and have thousands of users on my site so It would be great to switch to a plugin that is supported.

**Comment by swalkinshaw** [comment]
After a quick look at their source code it looks like it wouldn't generate the same hashes. So it's not a drop-in replacement. If you wanted to switch, you'd have to write some migration code yourself.
